error-exit

diff --git a/bin/bundle/iso-burn b/bin/bundle/iso-burn
--- a/bin/bundle/iso-burn
+++ b/bin/bundle/iso-burn
@@ -27,15 +27,13 @@ fi
 
 # Check if valid disk
 if ! udevadm info -q property "${disk}" | grep -qs "DEVTYPE=disk"; then
-    print-error "${disk} is not a disk!"
-    exit 1
+    error-exit "${disk} is not a disk!"
 fi
 
 # Check if USB
 if ! udevadm info -q property "${disk}" | grep -qs "ID_BUS=usb"; then
     echo
-    print-error "This device is not an USB stick!"
-    exit 1
+    error-exit "This device is not an USB stick!"
 fi
 
 # Unmount
@@ -50,7 +48,7 @@ done <<< "${mount_points}"
 
 print-header "Burning ISO to USB..."
 read -r -p "Are you sure? (y/n) ";
-[[ ${REPLY} == 'y' || ${REPLY} == 'Y' ]] || { echo "Aborted."; exit 1;}
+[[ ${REPLY} == 'y' || ${REPLY} == 'Y' ]] || error-exit "Aborted."
 sudo dd if="${iso_image}" bs=1M of="${disk}" oflag=sync,noatime status=progress
 print-finish
 
